### ISSUE TITLE
[Wrath & Glory System] Origin / Accomplishment / Goal Not Saving when typed in.

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#162]
tried as Trusted Player and GM on character<br/>**From**: Michael Mars#8075<br/>wrath-and-glory: 4.0.1

**Comment by thul** [comment]
I don't feel this is a bug, but more of a confusing part of functionality. Yes you can type in the input fields, but it won't get saved. This is because the value of these fields are linked to the Faction which the character belongs to.

![image](https://user-images.githubusercontent.com/1921331/190629719-10629fcf-03a1-4018-9638-0a363183282f.png)

Perhaps making these fields read-only or some using some other way to infer you can not type these out yourself but infact need to use an archetype which has a faction attached to it, would be a lot better.

**Comment by MichaelMarsGaming** [comment]
Adding the faction didn't prompt to add those and they can't be drag and dropped from the faction though.

**Comment by thul** [comment]
> Adding the faction didn't prompt to add those and they can't be drag and dropped from the faction though.
You need to use the Character creator, drop an archetype on the character sheet. The archetype has a faction attached

**Comment by MichaelMarsGaming** [comment]
Character Creator isn't used for advanced character creation and custom archetypes don't currently work. Plus some people may want to customize text for their backstory. I guess it could also be a drop down if custom text is that bad. Either way the character sheet should function without using the wizard IMO since there are valid options in the book for not using archetypes
