### ISSUE TITLE
Dice roller error

### ISSUE THREAD

**Issue by GaeTob80** [moo-man/WrathAndGlory-FoundryVTT#2]
The only dice results, from character sheet, are 6, 1 or nothing.

**Comment by ChrisselS** [comment]
Thats "normal". The System only shows icons and a 1 on wrath dice. The original Version of Perfectro had the aquila for icons and a chaos symbol vor a 1 on wrath dice. I don't know why it got changed, maybe because of image rights. 
You can change the pictures in the Symbol folder urself if you want.

Back to topic:
A red black 6 is one icon. A red 6 are two Icons.
A one on the wrath dice (the red dice) is a critical failure.
No Symbol means no Icon, obviously. The red one is the Wrath dice.

**Comment by GaeTob80** [comment]
Thank you.
It had actually irritated me that every success was displayed with a 6.

After I changed the images it fits.

Thanks for your work.
