### ISSUE TITLE
[WRath & Glory: Redacted Records I] Blademaster Talent is not applying.

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#201]
Essentially, neither effect for Blademaster is applying. My only thought is that, because of the "Change Mode" being "Targeter's Dialog Effect", the two scripts (to simulate Parry on a weapon with Blade and simulate the increase of Parry's benefit) don't proc because it's relying on the Targeter, not the holder of the Active Effect.
However, the Parry weapon trait and its effects work perfectly.<br/>**From**: TitaniumDragoonNeo#9580<br/>wrath-and-glory: 4.1.0

**Comment by titaniumdragoonneo** [comment]
Update. I believe it may come down to "Targeter's Dialog Effect", because modifiers to dice pool or difficulty that aren't tied down to any other restrictions (ie. weapon specifics or certain skills) aren't showing any change. I wonder if it's a issue of token targeting? Since the default attribute key _technically_ is "this.difficulty.base," or something like that. Essentially, I think it's a variable pointer/attribution issue.

**Comment by titaniumdragoonneo** [comment]
Another update, using a weapon with equipped ammunition gets the Blademaster dialog prompts to spawn on the Targeter's roll window, but with no effects applied when selected.
